Repository opentensor/subtensor, pull requests merged in 2024-07, with the labels that each got.

#602 Fix/no reg emissions
  justfile
  pallets/subtensor/src/block_step.rs
  pallets/subtensor/tests/block_step.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip

#485 Ban unsafe arithmetic operations
  Cargo.toml
  node/src/chain_spec/finney.rs
  node/src/chain_spec/testnet.rs
  pallets/admin-utils/src/benchmarking.rs
  pallets/admin-utils/tests/mock.rs
  pallets/collective/src/benchmarking.rs
  pallets/collective/src/lib.rs
  pallets/collective/src/tests.rs
  pallets/commitments/src/benchmarking.rs
  pallets/commitments/src/lib.rs
  pallets/commitments/src/types.rs
  pallets/registry/src/benchmarking.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/types.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/block_step.rs
  pallets/subtensor/src/delegate_info.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/serving.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/src/subnet_info.rs
  pallets/subtensor/src/uids.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/src/weights.rs
  pallets/subtensor/tests/block_step.rs
  pallets/subtensor/tests/difficulty.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/migration.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/root.rs
  pallets/subtensor/tests/senate.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/uids.rs
  pallets/subtensor/tests/weights.rs
  runtime/src/check_nonce.rs
  runtime/src/lib.rs
  runtime/tests/metadata.rs
  runtime/tests/pallet_proxy.rs
Labels: blue team, devnet-pass, testnet-pass

#561 Override default pages to fix archive sync
  node/src/command.rs
Labels: devnet-pass, on-testnet, testnet-pass

#552 feat: liquid alpha
  .github/workflows/check-devnet.yml
  .github/workflows/check-finney.yml
  .github/workflows/check-rust.yml
  .github/workflows/check-testnet.yml
  .gitignore
  Cargo.lock
  justfile
  pallets/admin-utils/Cargo.toml
  pallets/admin-utils/src/lib.rs
  pallets/admin-utils/tests/mock.rs
  pallets/admin-utils/tests/tests.rs
  pallets/subtensor/Cargo.toml
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/src/subnet_info.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/math.rs
  pallets/subtensor/tests/mock.rs
  runtime/src/lib.rs
  scripts/specs/local.json
  scripts/test_specific.sh
  zepter.yaml
Labels: devnet-pass, on-devnet, testnet-pass

#553 Implement safe mode pallet
  Cargo.lock
  Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: devnet-pass, testnet-pass

#607 Implement safe mode pallet on finney
  Cargo.lock
  Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip

#609 whitelist subtensor calls during safe mode
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip, hotfix

#556 Refactor/hotkey swap
  justfile
  pallets/admin-utils/tests/mock.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/serving.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
Labels: devnet-pass, testnet-pass

#612 Emergency
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip, hotfix

#611 Feat/cold key swap
  justfile
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
  scripts/test_specific.sh
Labels: devnet-skip, testnet-skip

#614 adds tests fixes remove hotkey
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/tests/staking.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip, hotfix

#619 Extend Safe Mode Extend
  pallets/subtensor/src/migration.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip

#586 always run e2e tests on all pull requests and on push for major branches
  .github/workflows/e2e-bittensor-tests.yml
Labels: devnet-skip, testnet-skip

#620 Schedule Coldkey Swap
  node/src/rpc.rs
  pallets/admin-utils/tests/mock.rs
  pallets/subtensor/rpc/src/lib.rs
  pallets/subtensor/runtime-api/src/lib.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/delegate_info.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/schedule_coldkey_swap_info.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
  scripts/benchmark.sh
Labels: devnet-pass, testnet-pass

#627 chore: remove coldkey swap rpc
  node/src/rpc.rs
  pallets/subtensor/rpc/src/lib.rs
  pallets/subtensor/runtime-api/src/lib.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/schedule_coldkey_swap_info.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip

#490 Fix Senate membership changes
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/senate.rs
Labels: red team, devnet-pass, testnet-pass

#631 Resuming the network
  pallets/admin-utils/tests/mock.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip

#629 merge main into devnet-ready 7-12-2024
  .github/workflows/e2e-bittensor-tests.yml
  .gitignore
  Dockerfile
  docs/running-subtensor-locally.md
  docs/rust-setup.md
  justfile
  pallets/admin-utils/scripts/benchmark.sh
  pallets/admin-utils/tests/mock.rs
  pallets/collective/src/lib.rs
  pallets/commitments/scripts/benchmark.sh
  pallets/registry/scripts/benchmark.sh
  pallets/registry/src/types.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/block_step.rs
  pallets/subtensor/src/delegate_info.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/block_step.rs
  pallets/subtensor/tests/math.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/check_nonce.rs
  runtime/src/lib.rs
  scripts/benchmark.sh
  scripts/build.sh
  scripts/run/subtensor.sh
  scripts/specs/local.json
  scripts/test_specific.sh
  support/macros/src/lib.rs
Labels: devnet-companion

#636 Total coldkey migration
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/tests/migration.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip

#644 Fix issues with Subtensor storage versions
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/tests/migration.rs
Labels: devnet-skip, testnet-skip

#645 Fix/total coldkey stake migration; clear map first
  pallets/subtensor/src/migration.rs
  pallets/subtensor/tests/migration.rs
  pallets/subtensor/tests/staking.rs
Labels: devnet-skip, testnet-skip

#650 Merge main into devnet ready 7 18 2024
  pallets/admin-utils/tests/mock.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/migration.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
Labels: devnet-companion

#628 [devnet-companion] Make weighted_median iterative
  pallets/subtensor/src/math.rs
Labels: devnet-companion

#649 Feat/devnet companion/check metadata hash extension
  Cargo.lock
  Cargo.toml
  justfile
  node/Cargo.toml
  node/src/benchmarking.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
  scripts/build.sh
Labels: devnet-companion

#664 Revert "Merge branch 'devnet-ready' into main"
  Cargo.lock
  Cargo.toml
  justfile
  node/Cargo.toml
  node/src/benchmarking.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/tests/mock.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
  scripts/build.sh
Labels: devnet-skip, testnet-skip

#666 Rebase devnet
  Cargo.lock
  Cargo.toml
  justfile
  node/Cargo.toml
  node/src/benchmarking.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/tests/mock.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
  scripts/build.sh
Labels: devnet-companion

#656 Removing from the "main" branch the doc to run subtensor locally
  docs/running-subtensor-locally.md
Labels: devnet-skip, testnet-skip

#674 [devnet-ready] [clippy] fix clippy warnings
  pallets/subtensor/tests/swap_hotkey.rs
Labels: devnet-companion

#672 Feat/devnet companion/check metadata hash extension
  Cargo.lock
  Cargo.toml
  justfile
  node/Cargo.toml
  node/src/benchmarking.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
  scripts/build.sh
Labels: devnet-companion

#657 Update README.md
  README.md
Labels: devnet-skip, testnet-skip

#687 try state for total issuance done
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/macros/hooks.rs
  pallets/subtensor/src/migrations/migrate_init_total_issuance.rs
  pallets/subtensor/src/migrations/mod.rs
  pallets/subtensor/src/staking/helpers.rs
  pallets/subtensor/src/utils/misc.rs
  pallets/subtensor/src/utils/mod.rs
  pallets/subtensor/src/utils/rate_limiting.rs
  pallets/subtensor/src/utils/try_state.rs
  pallets/subtensor/tests/migration.rs
  runtime/src/lib.rs
Labels: devnet-companion

#688 Swap parents children
  pallets/subtensor/src/swap/swap_hotkey.rs
  pallets/subtensor/tests/swap_hotkey.rs
Labels: devnet-companion

#690 Add Chain IDS
  .rustfmt.toml
  Cargo.lock
  docs/delegate-info.json
  pallets/subtensor/Cargo.toml
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/macros/dispatches.rs
  pallets/subtensor/src/macros/errors.rs
  pallets/subtensor/src/macros/events.rs
  pallets/subtensor/src/migrations/migrate_chain_identity.rs
  pallets/subtensor/src/migrations/mod.rs
  pallets/subtensor/src/utils/identity.rs
  pallets/subtensor/src/utils/mod.rs
  pallets/subtensor/tests/serving.rs
Labels: devnet-companion

#693 devnet fix clippy & unit test
  pallets/collective/src/lib.rs
  pallets/subtensor/Cargo.toml
  pallets/subtensor/tests/children.rs
  pallets/subtensor/tests/coinbase.rs
  pallets/subtensor/tests/difficulty.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/neuron_info.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/serving.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/weights.rs
  runtime/src/lib.rs
Labels: devnet-companion

#675 Added `--no-purge` flag to `scripts/localnet.sh` to be able to save state when restarting a script.
  runtime/src/lib.rs
  scripts/localnet.sh
Labels: blue team, devnet-skip, testnet-skip, devnet-companion
