Repository opentensor/subtensor, pull requests merged in 2024-05, with the labels that each got.

#387 Upgrade to polkadot-sdk-v1.10.0
  Cargo.lock
  Cargo.toml
  Dockerfile
  integration-tests/Cargo.toml
  integration-tests/src/main.rs
  node/Cargo.toml
  node/src/benchmarking.rs
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/service.rs
  pallets/admin-utils/Cargo.toml
  pallets/admin-utils/src/lib.rs
  pallets/admin-utils/tests/mock.rs
  pallets/collective/Cargo.toml
  pallets/collective/src/lib.rs
  pallets/collective/src/tests.rs
  pallets/commitments/Cargo.toml
  pallets/commitments/src/benchmarking.rs
  pallets/commitments/src/lib.rs
  pallets/commitments/src/tests.rs
  pallets/registry/Cargo.toml
  pallets/registry/src/benchmarking.rs
  pallets/subtensor/Cargo.toml
  pallets/subtensor/rpc/Cargo.toml
  pallets/subtensor/rpc/src/lib.rs
  pallets/subtensor/runtime-api/Cargo.toml
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/src/migration.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/uids.rs
  pallets/subtensor/src/weights.rs
  pallets/subtensor/tests/batch_tx.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/senate.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/migrations/account_data_migration.rs
  runtime/src/migrations/init_storage_versions.rs
  runtime/tests/pallet_proxy.rs
  scripts/husky.sh
Labels: blue team

#335 Add set_root_weights()
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/weights.rs
  pallets/subtensor/tests/root.rs
  pallets/subtensor/tests/weights.rs
Labels: breaking-change

#391 Fix the metadata
  .gitignore
  Cargo.lock
  Cargo.toml
  pallets/admin-utils/src/lib.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  runtime/Cargo.toml
  runtime/tests/metadata.rs
Labels: blue team

#397 fix: genesis config builder
  Cargo.lock
  Cargo.toml
  node/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: blue team

#398 ci: clippy deny warnings
  .github/workflows/check-rust.yml
  Cargo.toml
  pallets/admin-utils/tests/tests.rs
  pallets/collective/src/tests.rs
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/uids.rs
  pallets/subtensor/src/utils.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/migrations/account_data_migration.rs
  runtime/tests/metadata.rs
Labels: blue team

#408 fix: bump development spec version
  runtime/src/lib.rs
Labels: blue team

#407 fix: bump testnet spec version
  runtime/src/lib.rs
Labels: blue team

#413 feat: allow invoking localnet.sh from anywhere
  scripts/localnet.sh
Labels: blue team

#400 Documentation improvement for runtime
  pallets/admin-utils/src/lib.rs
  pallets/admin-utils/tests/tests.rs
  pallets/collective/src/lib.rs
  pallets/commitments/src/lib.rs
  pallets/registry/src/lib.rs
  pallets/subtensor/src/block_step.rs
  pallets/subtensor/src/delegate_info.rs
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/events.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/serving.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/src/uids.rs
  pallets/subtensor/src/weights.rs
Labels: documentation, blue team

#434 feat: e2e bittensor tests
  .github/workflows/check-rust.yml
  .github/workflows/e2e-bittensor-tests.yml
  node/src/chain_spec.rs
Labels: blue team

#450 chore: use staging branch e2e tests
  .github/workflows/e2e-bittensor-tests.yml
Labels: blue team

#433 Improve errors definition and docs
  pallets/admin-utils/src/lib.rs
  pallets/collective/src/lib.rs
  pallets/collective/src/tests.rs
  pallets/commitments/src/lib.rs
  pallets/registry/src/lib.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/serving.rs
  pallets/subtensor/src/staking.rs
  pallets/subtensor/src/uids.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/src/weights.rs
  pallets/subtensor/tests/networks.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/root.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/weights.rs
Labels: blue team

#459 chore: remove applied migrations
  .github/workflows/check-rust.yml
  runtime/src/lib.rs
  runtime/src/migrations/account_data_migration.rs
  runtime/src/migrations/init_storage_versions.rs
  runtime/src/migrations/mod.rs
Labels: blue team

#481 feat: localnet fast blocks
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/localnet.sh
Labels: blue team

#346 new development/deployment/release process
  .github/workflows/check-devnet.yml
  .github/workflows/check-finney.yml
  .github/workflows/check-rust.yml
  .github/workflows/check-testnet.yml
  .github/workflows/devnet-labels.yml
  .github/workflows/label-triggers.yml
  .github/workflows/testnet-labels.yml
  CONTRIBUTING.md
  runtime/Cargo.toml
  runtime/src/spec_version.rs
Labels: devnet-skip, testnet-skip

#479 feat: bad blocks chain extension
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/chain_spec/finney.rs
  node/src/chain_spec/localnet.rs
  node/src/chain_spec/mod.rs
  node/src/chain_spec/testnet.rs
  node/src/command.rs
  scripts/localnet.sh
Labels: blue team
