Repository opentensor/subtensor, pull requests merged in 2024-11, with the labels that each got.

#913 Fix/merge conflicts testnet mainnet
  pallets/subtensor/src/swap/swap_hotkey.rs
  pallets/subtensor/tests/swap_hotkey.rs
  support/procedural-fork/src/pallet/parse/storage.rs
  support/procedural-fork/src/runtime/parse/mod.rs
Labels: no-spec-version-bump, skip-cargo-audit

#933 Hotfix/skip root for emission accum
  pallets/subtensor/src/coinbase/run_coinbase.rs
Labels: skip-cargo-audit

#936 use chk for neuron info lite stake
  pallets/subtensor/src/rpc_info/neuron_info.rs
Labels: skip-cargo-audit

#934 Hotfix/clear stake delta on drain
  pallets/subtensor/src/coinbase/run_coinbase.rs
  pallets/subtensor/src/staking/helpers.rs
  pallets/subtensor/src/staking/remove_stake.rs
  pallets/subtensor/src/swap/swap_coldkey.rs
  pallets/subtensor/tests/coinbase.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap_coldkey.rs
Labels: skip-cargo-audit

#941 Hotfixes to testnet nov 6
  pallets/subtensor/src/coinbase/run_coinbase.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/rpc_info/neuron_info.rs
  pallets/subtensor/src/staking/helpers.rs
  pallets/subtensor/src/staking/remove_stake.rs
  pallets/subtensor/src/subnets/uids.rs
  pallets/subtensor/src/subnets/weights.rs
  pallets/subtensor/src/swap/swap_coldkey.rs
  pallets/subtensor/tests/children.rs
  pallets/subtensor/tests/coinbase.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap_coldkey.rs
  pallets/subtensor/tests/weights.rs
  runtime/src/lib.rs
Labels: skip-cargo-audit

#930 fix: host functions (main)
  node/src/service.rs
Labels: skip-cargo-audit

#953 add bot warning when posting a hotfix PR
  .github/workflows/hotfixes.yml
Labels: blue team, no-spec-version-bump

#959 Hotfix Chainspec Build
  scripts/build_all_chainspecs.sh
Labels: no-spec-version-bump, skip-cargo-audit

#962 backpropagate hotfixes to testnet
  scripts/build_all_chainspecs.sh
Labels: no-spec-version-bump, skip-cargo-audit

#927 Lint `ForbidKeysRemoveCall`
  build.rs
  pallets/subtensor/src/subnets/uids.rs
  support/linting/src/forbid_as_primitive.rs
  support/linting/src/forbid_keys_remove.rs
  support/linting/src/lib.rs
  support/linting/src/lint.rs
Labels: no-spec-version-bump

#984 fix EVM <=> TAO balance transfer precision
  .github/workflows/cargo-audit.yml
  .github/workflows/check-devnet.yml
  .github/workflows/check-finney.yml
  .github/workflows/check-rust.yml
  .github/workflows/check-testnet.yml
  .github/workflows/try-runtime.yml
  runtime/src/lib.rs
  runtime/src/precompiles/balance_transfer.rs
Labels: bug
