Repository opentensor/subtensor, pull requests merged in 2024-06, with the labels that each got.

#499 fix: write permissions for ci packages
  .github/workflows/docker.yml
Labels: devnet-skip, testnet-skip

#527 hotfix/set-root-weights
  .github/workflows/check-rust.yml
  node/src/rpc.rs
  node/src/service.rs
  pallets/admin-utils/src/lib.rs
  pallets/commitments/src/lib.rs
  pallets/registry/src/lib.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/weights.rs
  pallets/subtensor/tests/block_step.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/weights.rs
  runtime/src/check_nonce.rs
  runtime/src/lib.rs
  scripts/localnet.sh
Labels: devnet-skip, testnet-skip

#538 only apply devnet-pass/testnet-pass label check to PRs on main
  .github/workflows/devnet-labels.yml
  .github/workflows/testnet-labels.yml
Labels: devnet-skip, testnet-skip

#550 [devnet companion] prevent accidental changes to storage structs
  .cargo-husky/hooks/prepare-commit-msg
  .github/workflows/check-rust.yml
  .github/workflows/devnet-labels.yml
  .github/workflows/testnet-labels.yml
  CITATION.cft
  Cargo.lock
  Cargo.toml
  Dockerfile
  node/src/rpc.rs
  node/src/service.rs
  pallets/admin-utils/Cargo.toml
  pallets/admin-utils/src/lib.rs
  pallets/collective/Cargo.toml
  pallets/collective/src/lib.rs
  pallets/commitments/Cargo.toml
  pallets/commitments/src/lib.rs
  pallets/commitments/src/types.rs
  pallets/registry/Cargo.toml
  pallets/registry/src/lib.rs
  pallets/registry/src/types.rs
  pallets/subtensor/Cargo.toml
  pallets/subtensor/src/delegate_info.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/src/neuron_info.rs
  pallets/subtensor/src/root.rs
  pallets/subtensor/src/stake_info.rs
  pallets/subtensor/src/subnet_info.rs
  pallets/subtensor/src/weights.rs
  pallets/subtensor/tests/block_step.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/weights.rs
  runtime/Cargo.toml
  runtime/src/check_nonce.rs
  runtime/src/lib.rs
  scripts/localnet.sh
  support/macros/Cargo.toml
  support/macros/src/lib.rs
  support/macros/src/visitor.rs
  support/macros/tests/tests.rs
Labels: devnet-companion

#554 [devnet-companion] prevent accidental changes to storage structs (2)
  support/macros/src/lib.rs
Labels: devnet-companion

#551 add CI check for companion labels, update deployment docs
  .github/workflows/devnet-ready-labels.yml
  .github/workflows/testnet-ready-labels.yml
  CONTRIBUTING.md
Labels: blue team, devnet-skip, testnet-skip

#559 [devnet-companion] safe mode
  Cargo.lock
  Cargo.toml
  pallets/registry/src/types.rs
  pallets/subtensor/src/subnet_info.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: devnet-companion

#562 Override default pages to fix archive sync [devnet-ready]
  docs/running-subtensor-locally.md
  node/src/command.rs
Labels: devnet-companion

#568 Devnet companion feat/liquid alpha 2
  .github/workflows/check-devnet.yml
  .github/workflows/check-finney.yml
  .github/workflows/check-rust.yml
  .github/workflows/check-testnet.yml
  Cargo.lock
  justfile
  pallets/admin-utils/Cargo.toml
  pallets/admin-utils/src/lib.rs
  pallets/admin-utils/tests/mock.rs
  pallets/admin-utils/tests/tests.rs
  pallets/subtensor/Cargo.toml
  pallets/subtensor/src/epoch.rs
  pallets/subtensor/src/errors.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/math.rs
  pallets/subtensor/src/subnet_info.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/math.rs
  pallets/subtensor/tests/mock.rs
  runtime/src/lib.rs
  scripts/test_specific.sh
  zepter.yaml
Labels: devnet-companion

#567 [devnet companion]refactor/hotkey swap
  .github/workflows/devnet-ready-labels.yml
  .github/workflows/testnet-ready-labels.yml
  CONTRIBUTING.md
  pallets/admin-utils/tests/mock.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/registration.rs
  pallets/subtensor/src/swap.rs
  pallets/subtensor/src/utils.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/serving.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/swap.rs
  runtime/src/lib.rs
Labels: devnet-companion

#571 Update spec file usage
  docker-compose.yml
  docs/running-subtensor-locally.md
  scripts/run/subtensor.sh
Labels: devnet-companion

#583 Feat/adjust senate benchmarks
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/lib.rs
  runtime/src/lib.rs
  scripts/benchmark.sh
Labels: devnet-companion

#573 update one error comment
  pallets/subtensor/src/errors.rs
Labels: blue team, devnet-skip, testnet-skip

#565 Document production profile
  Dockerfile
  docs/running-subtensor-locally.md
  docs/rust-setup.md
  pallets/admin-utils/scripts/benchmark.sh
  pallets/commitments/scripts/benchmark.sh
  pallets/registry/scripts/benchmark.sh
  scripts/benchmark.sh
  scripts/build.sh
  scripts/run/subtensor.sh
Labels: devnet-skip, testnet-skip
