Repository opentensor/subtensor, pull requests merged in 2024-08, with the labels that each got.

#692 Only run spec version check when the skip label doesn't exist
  .github/workflows/check-finney.yml
  pallets/collective/src/lib.rs
Labels: devnet-skip, testnet-skip, no-spec-version-bump

#716 switch back to the old deploy/release process
  .github/workflows/check-devnet.yml
  .github/workflows/check-rust.yml
  .github/workflows/check-testnet.yml
  .github/workflows/devnet-labels.yml
  .github/workflows/devnet-ready-labels.yml
  .github/workflows/testnet-labels.yml
  .github/workflows/testnet-ready-labels.yml
  CONTRIBUTING.md
Labels: no-spec-version-bump

#718 fix clippy
  pallets/subtensor/src/lib.rs
  pallets/subtensor/tests/difficulty.rs
  pallets/subtensor/tests/epoch.rs
  pallets/subtensor/tests/mock.rs
  pallets/subtensor/tests/neuron_info.rs
  pallets/subtensor/tests/registration.rs
  pallets/subtensor/tests/serving.rs
  pallets/subtensor/tests/staking.rs
  pallets/subtensor/tests/weights.rs
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip, hotfix, no-spec-version-bump

#714 Bump `main` spec version
  runtime/src/lib.rs
Labels: devnet-skip, testnet-skip, hotfix

#715 Bump `testnet` spec version
  runtime/src/lib.rs
Labels: devnet-skip, hotfix

#734 Include the devnet-ready branch when checking for deployment
  .github/workflows/check-devnet.yml
  .github/workflows/check-testnet.yml
Labels: devnet-skip, testnet-skip, no-spec-version-bump

#732 Sensible runtime log level
  pallets/admin-utils/src/lib.rs
  pallets/subtensor/src/coinbase/root.rs
  pallets/subtensor/src/epoch/run_epoch.rs
  pallets/subtensor/src/macros/hooks.rs
  pallets/subtensor/src/rpc_info/delegate_info.rs
  pallets/subtensor/src/staking/add_stake.rs
  pallets/subtensor/src/staking/become_delegate.rs
  pallets/subtensor/src/staking/decrease_take.rs
  pallets/subtensor/src/staking/increase_take.rs
  pallets/subtensor/src/staking/remove_stake.rs
  pallets/subtensor/src/subnets/registration.rs
  pallets/subtensor/src/subnets/serving.rs
  pallets/subtensor/src/subnets/weights.rs
  pallets/subtensor/src/utils/identity.rs
  pallets/subtensor/src/utils/misc.rs
Labels: bug, blue team, no-spec-version-bump

#709 Replace SubtensorInterface with tight pallet coupling
  pallets/admin-utils/src/benchmarking.rs
  pallets/admin-utils/src/lib.rs
  pallets/admin-utils/tests/mock.rs
  runtime/src/lib.rs
Labels: devnet-companion

#744 fix broken workspace root package
  Cargo.lock
  Cargo.toml
Labels: no-spec-version-bump

#764 Fix pallet indicies and specify them explicitly
  runtime/src/lib.rs
Labels: no-spec-version-bump
