Repository opentensor/subtensor, pull requests merged in 2025-01, with the labels that each got.

#1168 make docker image builds trigger on key branches + ability to manually trigger
  .github/workflows/docker.yml
Labels: blue team, no-spec-version-bump, skip-cargo-audit

#1141 Fix/charge-for-swap-before-schedule
  pallets/subtensor/src/benchmarks.rs
  pallets/subtensor/src/macros/dispatches.rs
  pallets/subtensor/src/macros/events.rs
  pallets/subtensor/src/swap/swap_coldkey.rs
  pallets/subtensor/src/tests/swap_coldkey.rs
  runtime/src/lib.rs
Labels: skip-cargo-audit

#1152 Fix/per 1k estimate always zero
  pallets/subtensor/src/rpc_info/delegate_info.rs
  pallets/subtensor/src/tests/delegate_info.rs
  pallets/subtensor/src/tests/mod.rs
Labels: skip-cargo-audit

#1175 Metagraph struct
  Cargo.lock
  pallets/subtensor/rpc/src/lib.rs
  pallets/subtensor/runtime-api/src/lib.rs
  pallets/subtensor/src/rpc_info/metagraph.rs
  pallets/subtensor/src/rpc_info/mod.rs
  runtime/src/lib.rs
Labels: skip-cargo-audit

#1160 Add bonds_penalty hyperparam
  hyperparameters.md
  pallets/admin-utils/src/benchmarking.rs
  pallets/admin-utils/src/lib.rs
  pallets/admin-utils/src/tests/mock.rs
  pallets/admin-utils/src/tests/mod.rs
  pallets/admin-utils/src/weights.rs
  pallets/subtensor/src/epoch/math.rs
  pallets/subtensor/src/epoch/run_epoch.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/macros/config.rs
  pallets/subtensor/src/macros/events.rs
  pallets/subtensor/src/tests/epoch.rs
  pallets/subtensor/src/tests/math.rs
  pallets/subtensor/src/tests/mock.rs
  pallets/subtensor/src/utils/misc.rs
  runtime/src/lib.rs
Labels: no-spec-version-bump, skip-cargo-audit

#1171 Fix/run set pending children on epoch
  pallets/subtensor/src/coinbase/block_step.rs
  pallets/subtensor/src/tests/children.rs
  pallets/subtensor/src/tests/epoch.rs
  pallets/subtensor/src/tests/mock.rs
  pallets/subtensor/src/tests/move_stake.rs
  pallets/subtensor/src/tests/registration.rs
  pallets/subtensor/src/tests/senate.rs
  pallets/subtensor/src/tests/staking.rs
  pallets/subtensor/src/tests/swap_hotkey.rs
  pallets/subtensor/src/tests/weights.rs
  runtime/src/lib.rs
Labels: skip-cargo-audit
