Repository opentensor/subtensor, pull requests merged in 2025-03, with the labels that each got.

#1359 fix docker build process + ARM support
  .github/workflows/docker.yml
  Dockerfile
Labels: blue team

#1397 Hotfix/bound hyp params
  Cargo.lock
  pallets/admin-utils/src/lib.rs
  pallets/subtensor/src/lib.rs
  pallets/subtensor/src/macros/errors.rs
  runtime/src/lib.rs
Labels: hotfix

#1412 Fix Dockerfile-localnet name
  .github/workflows/docker-localnet.yml
Labels: skip-cargo-audit

#1414 Fix and improvement
  .github/workflows/check-docker-localnet.yml
Labels: skip-cargo-audit

#1428 Feat/record initial subnet tao in totalstake
  .github/workflows/try-runtime.yml
  pallets/subtensor/src/migrations/migrate_dissolve_sn73.rs
  pallets/subtensor/src/migrations/migrate_init_total_issuance.rs
  pallets/subtensor/src/subnets/subnet.rs
  pallets/subtensor/src/tests/migration.rs
  pallets/subtensor/src/tests/staking.rs
  pallets/subtensor/src/utils/try_state.rs
  runtime/src/lib.rs
Labels: skip-cargo-audit

#1472 feat/Multiple Revealed Commitments
  pallets/commitments/src/lib.rs
  pallets/commitments/src/mock.rs
  pallets/commitments/src/tests.rs
  pallets/subtensor/src/macros/hooks.rs
  pallets/subtensor/src/migrations/migrate_upgrade_revealed_commitments.rs
  pallets/subtensor/src/migrations/mod.rs
  pallets/subtensor/src/tests/migration.rs
  runtime/src/lib.rs
Labels: skip-cargo-audit, run-bittensor-e2e-tests
